name: "github"
services:
  runner01:
    runtime: sysbox-runc
    deploy:
      resources:
        limits:
          cpus: '8.00'
          memory: 4G
    image: "11notes/github-runner:2.325.0"
    environment:
      TZ: "Europe/Zurich"
      RUNNER_NAME: "runner01"
      RUNNER_REPO: "11notes/docker-node"
      RUNNER_ADMINISTRATION_TOKEN: ${RUNNER_ADMINISTRATION_TOKEN}
    volumes:
      - "var:/runner"
    restart: "always"

volumes:
  var: