name: "github"
services:
  runner:
    deploy:
      resources:
        limits:
          cpus: '24.00'
          memory: 16G
        reservations:
          cpus: '1.00'
          memory: 1G
    image: "11notes/github-runner:2.323.0"
    container_name: "docker-node-runner01"
    hostname: "docker-node-runner01"
    environment:
      TZ: "Europe/Zurich"
      GITHUB_REPOSITORY: "11notes/docker-node"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - "/run/docker.sock:/var/run/docker.sock:ro"
      - "var:/home/runner"
    restart: "always"

volumes:
  var: